name: deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Trigger Destroy Manually'
        required: true
        default: 'false'

jobs:
  plan:
    name: Terraform Plan & Deploy
    runs-on: ubuntu-latest
    if: github.event.inputs.manual_trigger == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_CL_TOKEN }}

      - name: Terraform Init

        run: |
          terraform init -get=true -upgrade

      - name: Terraform format
        id: fmt
        run: terraform fmt

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
