name: Destroy

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Trigger Destroy Manually'
        required: true
        default: 'false'

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: github.event.inputs.manual_trigger == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4
          cli_config_credentials_token: ${{ secrets.TF_CL_TOKEN }}

      - name: Terraform Init
        run: |
          terraform init -get=true -upgrade

      - name: Terraform Destroy
        run: terraform destroy -auto-approve